/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Advertise: typeof import('./src/components/index/Advertise.vue')['default']
    Banner: typeof import('./src/components/index/Banner.vue')['default']
    ButtonNavigate: typeof import('./src/components/index/ButtonNavigate.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Gallery: typeof import('./src/components/index/Gallery.vue')['default']
    Gallory: typeof import('./src/components/index/Gallory.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Register: typeof import('./src/components/index/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
